"""
Data models for the SmartConnect Contact Management System.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Contact:
    """
    Contact data model representing a person's contact information.
    
    Attributes:
        id: Unique identifier for the contact (auto-generated by database)
        name: Full name of the contact (required)
        phone: Phone number in flexible format
        email: Email address
        address: Physical address
        company: Company or organization name
        job_title: Job title or position
        category: Contact category (Family, Friends, Work)
        created_at: Timestamp when contact was created
        updated_at: Timestamp when contact was last modified
    """
    id: Optional[int] = None
    name: str = ""
    phone: str = ""
    email: str = ""
    address: str = ""
    company: str = ""
    job_title: str = ""
    category: str = "Friends"  # Default category
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    
    def __post_init__(self):
        """Set timestamps if not provided."""
        if self.created_at is None:
            self.created_at = datetime.now()
        if self.updated_at is None:
            self.updated_at = datetime.now()